/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2019-07-01 01:06:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.main.inc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.HashMap;

public final class EgovIncLeftmenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String menuNo = ((String)session.getAttribute("menuNo")!=null)?(String)session.getAttribute("menuNo"):"11";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"nav\">\t\r\n");
      out.write("\t<div class=\"top\"></div>             \r\n");
      out.write("\t<div class=\"nav_style\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t    ");
 if (menuNo.indexOf("1")== 0) {
      out.write("\r\n");
      out.write("\t\t<li class=\"leftmenu_dept01\">\r\n");
      out.write("\t\t\t<a href=\"javascript:fn_main_headPageMove('11','main/sample_menu/EgovAboutSite')\">사이트소개</a>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"dept02\"><a href=\"javascript:fn_main_headPageMove('11','main/sample_menu/EgovAboutSite')\">소개</a></li>\t\r\n");
      out.write("\t\t\t\t<li class=\"dept02\"><a href=\"javascript:fn_main_headPageMove('12','main/sample_menu/EgovHistory')\">연혁</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"dept02\"><a href=\"javascript:fn_main_headPageMove('13','main/sample_menu/EgovOrganization')\">조직소개</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"dept02\"><a href=\"javascript:fn_main_headPageMove('14','main/sample_menu/EgovLocation')\">찾아오시는 길</a></li>\r\n");
      out.write("\t\t\t</ul> \r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t");
 if (menuNo.indexOf("2")== 0) {
      out.write("\r\n");
      out.write("\t\t<li class=\"leftmenu_dept01\">\r\n");
      out.write("\t\t\t<a href=\"javascript:fn_main_headPageMove('21','main/sample_menu/EgovProductInfo')\">정보마당</a>\r\n");
      out.write("\t\t\t<ul>\t\r\n");
      out.write("\t\t\t\t<li class=\"dept02\"><a href=\"javascript:fn_main_headPageMove('21','main/sample_menu/EgovProductInfo')\">주요사업 소개</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"dept02\"><a href=\"javascript:fn_main_headPageMove('22','main/sample_menu/EgovServiceInfo')\">대표서비스 소개</a></li>\r\n");
      out.write("\t\t\t</ul> \r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("        ");
 if (menuNo.indexOf("3")== 0) {
      out.write("\r\n");
      out.write("\t\t<li class=\"leftmenu_dept01\">\r\n");
      out.write("\t\t\t<a href=\"javascript:fn_main_headPageMove('31','main/sample_menu/EgovDownload')\">고객지원</a>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"dept02\"><a href=\"javascript:fn_main_headPageMove('31','main/sample_menu/EgovDownload')\">자료실</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"dept02\"><a href=\"javascript:fn_main_headPageMove('32','main/sample_menu/EgovQA')\">묻고답하기</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"dept02\"><a href=\"javascript:fn_main_headPageMove('33','main/sample_menu/EgovService')\">서비스신청</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("        ");
 if (menuNo.indexOf("4")== 0) {
      out.write("\r\n");
      out.write("\t\t<li class=\"leftmenu_dept01\">\r\n");
      out.write("\t\t\t<a href=\"javascript:fn_main_headPageAction('41','cop/smt/sim/EgovIndvdlSchdulManageDailyList.do')\">알림마당</a>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t    <li class=\"dept02\"><a href=\"javascript:fn_main_headPageAction('41','cop/smt/sim/EgovIndvdlSchdulManageDailyList.do')\">오늘의 행사</a></li>\t\r\n");
      out.write("\t\t\t\t<li class=\"dept02\"><a href=\"javascript:fn_main_headPageAction('42','cop/smt/sim/EgovIndvdlSchdulManageWeekList.do')\">금주의 행사</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"dept02\"><a href=\"javascript:fn_main_headPageAction('43','cop/bbs/selectBoardList.do?bbsId=BBSMSTR_AAAAAAAAAAAA')\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"dept02\"><a href=\"javascript:fn_main_headPageAction('44','cop/bbs/selectBoardList.do?bbsId=BBSMSTR_BBBBBBBBBBBB')\">사이트갤러리</a></li>\r\n");
      out.write("\t\t\t</ul> \r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("        ");
 if (menuNo.indexOf("5")== 0) {
      out.write("\r\n");
      out.write("\t\t<li class=\"leftmenu_dept01\">\r\n");
      out.write("\t\t\t<a href=\"javascript:fn_main_headPageAction('51','cop/smt/sim/EgovIndvdlSchdulManageMonthList.do')\">사이트관리</a>\r\n");
      out.write("\t\t\t<ul>\t\r\n");
      out.write("\t\t\t\t<li class=\"dept02\"><a href=\"javascript:fn_main_headPageAction('51','cop/smt/sim/EgovIndvdlSchdulManageMonthList.do')\">일정관리</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"dept02\"><a href=\"javascript:fn_main_headPageAction('52','cop/com/selectTemplateInfs.do')\">게시판템플릿관리</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"dept02\"><a href=\"javascript:fn_main_headPageAction('53','cop/bbs/SelectBBSMasterInfs.do')\">게시판생성관리</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"dept02\"><a href=\"javascript:fn_main_headPageAction('54','cop/com/selectBBSUseInfs.do')\">게시판사용관리</a></li> \r\n");
      out.write("\t\t\t\t<li class=\"dept02\"><a href=\"javascript:fn_main_headPageAction('55','cop/bbs/selectBoardList.do?bbsId=BBSMSTR_AAAAAAAAAAAA')\">공지사항관리</a></li>\r\n");
      out.write("                <li class=\"dept02\"><a href=\"javascript:fn_main_headPageAction('56','cop/bbs/selectBoardList.do?bbsId=BBSMSTR_BBBBBBBBBBBB')\">사이트갤러리관리</a></li>\r\n");
      out.write("\t\t\t</ul> \r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"bottom\"></div>\t\t\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //메뉴 끝 -->\t\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
